name: example schedule action

on:
  schedule:
    - cron: "10 * * * *"
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run scheduled task
        run: |
          echo "Custom script starting"
          echo "This is the date today $(date)"
          echo "success"