name: Multi Event Action
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Priting Basic information"
        run: | 
          while IFS='=' read -r -d name value; do 
          printf "Variable: '%s' = '%s'\\n" "$name" "$value"
          done < <(env -0)
          





